### ISSUE TITLE
App stuck on all workspaces

### ISSUE THREAD

**Issue by gr4kk3r** [fuhsjr00/bug.n#104]
Not sure if this is the right place, but I have a couple apps that when I open them they stay on every workspace. One is Telegram, and the other is a python/gtk app that I wrote. Is there a hotkey to make a window stay only on one workspace? If this is the wrong place to ask, please point me in the right direction. Thanks.

**Comment by x29a** [comment]
Hi, can you please provide [debug information](https://github.com/fuhsjr00/bug.n/blob/master/doc/Cheat_sheet/Default_hotkeys.md#window-debugging) 
when having your problematic windows open?

**Comment by joten** [comment]
This is quite the right place to ask.

It seems as if the windows you named are not managed by bug.n -- perhaps because they are recognized as pop-ups.

There is an undocumented function, `Manager_override(rule = "")`, you may use to reset those windows by hotkey (<kbd>Win</kbd><kbd>Ctrl</kbd><kbd>O</kbd>), if the window in question is active. Add tho following line to your Config.ini to 'activate' the function:

`Config_hotkey=#^o::Manager_override(1;0;0;0;1;0;)`

The persistent way to solve the problem would be to set the proper rules for those windows in your Config.ini. You may use the hotkey <kbd>Win</kbd><kbd>I</kbd> to retrieve the window information of the active window and get a sample rule, if copying it to the clipbard.

**Comment by gr4kk3r** [comment]
I just realized I never replied to say thanks. So, thanks joten, that worked out and wasn't very difficult.
