### ISSUE TITLE
Can't use trace areas

### ISSUE THREAD

**Issue by testingcan** [fuhsjr00/bug.n#118]
Currently using bug.n on Windows 7 and I can't get the trace areas to work. 

The `View_traceAreas()'-c`-command does nothing, setting `Config_continuouslyTraceAreas=0` to `1` changes nothing, changing the `areaTraceTimeout` does nothing. 

I already tried a different hotkey for the `View_traceAreas()`-command, but to no avail. 

I'm not sure if I'm doing anything wrong or where the error lies.

**Comment by joten** [comment]
I had a look at the source, and `View_traceAreas` only works, if in "tile layout" and in "manual tiling mode" (i. e. `Config_dynamicTiling=0`). It is a function specific to manual tiling. -- With dynamic tiling it should not be necessary to visually confirm the different tiling areas, since they are automatically populated anyway.

**Comment by testingcan** [comment]
Well yeah, that makes sense. Thanks. I've been wondering about this for a long time but could not figure this simple thing out.
