### ISSUE TITLE
Ability to show more than 1 tag at a time

### ISSUE THREAD

**Issue by ChrisPara** [fuhsjr00/bug.n#119]
It would be great to be able to show more than 1 tag at a time (i.e. bring/toggle other tags to the current view by shortcut).

Excuse me if that's already possible and I missed it. Otherwise, bug.n is working perfect for me, thanks for sharing it!

**Comment by joten** [comment]
> Excuse me if that's already possible and I missed it.

No, this is currently not possible. But you may add a tag to a window, therewith making it visible on more than one view.

**Comment by ChrisPara** [comment]
Thanks - yes, that's how I currently do it too!
I believe adding this would make the process faster / more flexible.

**Comment by ChrisPara** [comment]
...it would allow us to use this guy's workflow:
https://andrewwong.id.au/blog/dwm-tags-are-not-workspaces/

**Comment by joten** [comment]
Well, I considered this functionality at the beginning of writing bug.n and argued against it, being nice to have, but not necessary. It is relatively complex to implement, especially regading the window ordering in a "mixed" view.

Since I currently do not use Windows/bug.n myself, I am not working on this project.

**Comment by joten** [comment]
I copied this to issue #112 consolidating the view related enhancements request.
