### ISSUE TITLE
Be able to set monitor by absolute number

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#17]
I'd like to change monitor by giving its absolute number (like Xmonad does). Currently, `Manager_activateMonitor(d)` switches relatively to the current monitor.

I have done it empirically on a clone by replacing (in `Manager.ahk`) the call to `Manager_loop` in `Manager_activateMonitor` and `Manager_setWindowMonitor` by a version that starts from 1. It works, but I think a proper configurable solution would be nice.

**Comment by franckspike** [comment]
I implemented it, how can I commit ?

**Comment by joten** [comment]
Well, I like your enthusiasm!

I took a look at your fork, but did not see any additional commits.

The plan was -- well, still should be -- to...

1. Resolve most of the bugs.
2. Make the release for version 8.4.0
3. Initialize version 9.0.0
4. Make the enhancements.

The problem is, that, for the sake of consistency, the function in question should be implemented in the style matching `Monitor_activateView(v)`, which would change the UI, break compatibility and therefor should be in the next major release i. e. 9.0.0.

@fuhsjr00 We could, of course, speed up this process; it seems, there is not much new information regarding the bugs.

**Comment by franckspike** [comment]
(I am new to GitHub, I think) I just commited the functions for absolute monitor reference.

I'll have a look on the version 8.4.0 features/bugs

I also implemented a interprocess communication mechanism, to call functions from another process in order to control bug.n, but it's a bit creepy for now as it uses a hidden edit box for interprocess messaging.... I just want to let you know... this would need to cleaner though as it looks more like a hack...

**Comment by joten** [comment]
I implemented the feature with commit 7d7c20f7161ac0b3b14cc53f3b62ac9d686068ca.

You may add a hotkey e. g. by inserting the following line into your `Config.ini`: `Config_hotkey=!1::Manager_activateMonitor(1)` (if you are not using manual tiling).

I also revised i. a. the functions `Manager_setWindowMonitor` and `Manager_setViewMonitor` to allow setting an absolute value for the target monitor.

Please regard, that I made a lot of changes to function names and parameters, so that you may encounter problems with the current development version of bug.n and an outdated `Config.ini`.

**Comment by franckspike** [comment]
I'm used to svn and learning (cygwin's) git... I plan to update my master to your latest version and work on your bugs (and mine).. I should be in sync soon, hopefully!

**Comment by franckspike** [comment]
git pull gives me up-to-date, I guess I'm up-to-date with my fork on GitHub !?
Then can I update my GitHub fork to your latest version ?
Must I create a fork each time I wish someting to be pulled on your repository ?
What is the normal procedure for this kind of clone/branch/pull with your repository ?

**Comment by franckspike** [comment]
I'm on track with this all, I'll let you know if I'm stuck and need help :)

**Comment by franckspike** [comment]
I'm all sync'ed up, I'm having a look on the bug list to see if there's one that's particularely annoying to me right now

**Comment by joten** [comment]
> I'm having a look on the bug list

If you like, you may have a look at issues #5, #9 and #14 and see, if you can reproduce the problems; I never could, so that there is not much for me to go on.
