### ISSUE TITLE
Focus issues with Outlook 2013

### ISSUE THREAD

**Issue by jfmcbrayer** [fuhsjr00/bug.n#21]
If Outlook 2013 is running, I will eventually have focus problems with bug.n. The most common is that either Outlook cannot be focused, or Outlook will grab focus and not let it go. Occasionally there are other weirdnesses, such as Outlook composer or message windows re-opening themselves after being closed. Restarting bug.n may solve the problem for a while, but not reliably. Exiting Outlook always solves the problem.

I don't have very useful debugging information on this, but if you'll tell me how to gather some, I will.

**Comment by joten** [comment]
Currently, I cannot test Outlook; maybe I can get my hands on one next week.

As a workaround you can exclude Outlook from being tiled. https://github.com/fuhsjr00/bug.n/blob/master/doc/Customization.md and https://github.com/fuhsjr00/bug.n/blob/master/doc/Configuring_rules.md are useful resources. In short:
* Get the window information for Outlook by pressing the hotkey `Win+I` when Outlook (or Outlook Composer) is the active window.
* Open `Config.ini` by pressing the hotkey `Win+Ctrl+E`.
* Insert a new rule, which looks like this`Config_rule=rctrl_renwnd32;Outlook.*;;0;0;0;1;1;0;` (This is just a guess regarding the window class and title.).

**Comment by jfmcbrayer** [comment]
Excluding Outlook from being tiled works for now.

**Comment by Chadehoc** [comment]
Trying release 8.4.0, I get the same behaviour, not with Outlook but for example (none systematically reproductible):
* sometimes with the Explorer (from the appearance of the window),
* or with a TortoiseSVN window (which I have configured to be managed and floating) as soon as I try to tile it (with #t)
* or once with the Delphi IDE in a particular way: I opened a popup menu with the mouse, suddenly the drop-down disappeared while the menu entry remains in pushed state. Then impossible to leave focus.

I reverted to 8.3.1 because of the frequency of those focus problems. I tried to delete all the data folder (thinking of rubbish left from 8.3.1) but the problems eventually came back.

**Comment by joten** [comment]
I could reproduce the problem. @Chadehoc's description from issue #24 is, what I can corroborate:

> bug.n often gets stuck in a state where changing view, or even focus, becomes impossible.

But I can only deal with the problem at work and at work I have to -- well -- do my job. Therefor the bug fixing could take some time. So far I could not see any approach to the problem, since the windows themselves seem to be 'normal'.

**Comment by jfmcbrayer** [comment]
Commit b79369c1257ce961e56f52d2c573b45bb70ef256 *seems* to have fixed this bug. It could crop up later, I've only been testing it for half a day, but I would expect to have seen it by now.

**Comment by joten** [comment]
Yes, I tested it today, too. I leave the issue open until further testing, since I have still seen a glitch, which I have to figure out.

I took a different approach to handling shell messages and active-window-tracking, which needs some fine-tuning.

**Comment by jfmcbrayer** [comment]
Is the glitch that sometimes window close events are not noticed? Because that seems to happen to me -- I occasionally get a blank space in the stacking area.

**Comment by Chadehoc** [comment]
The bug seems fixed for me too !

I was close to adopting version 9.0.0 until I saw that all `Config_rule` calling `View_setLayoutProperty` do not work in my `config.ini` (just try to rebind them to a different key).

**Comment by joten** [comment]
> all `Config_rule` calling `View_setLayoutProperty` do not work in my `config.ini` (just try to rebind them to a different key).

`Config_hotkey=#Right::View_setLayoutProperty(MFactor, 0, -0.05)`
`Config_hotkey=#Left::View_setLayoutProperty(MFactor, 0, +0.05)`
..., which simply switches these hotkeys, did work for me.

**Comment by Chadehoc** [comment]
```
Config_hotkey=#Right::View_setLayoutProperty(MFactor, 0, -0.05)
Config_hotkey=#Left::View_setLayoutProperty(MFactor, 0, +0.05)
```
Ah, then this was a bug in the documentation of the default hotkeys, which wrongly puts double quotes around "MFactor" and all property names.

I suppose that  those examples come from the initial script where quotes are needed, but your parser doesn't.

**Comment by joten** [comment]
I tried a different approach to shell-message-handling. -- It didn't work out. In the end I couldn't fix the resulting problems and therefor reverted back to the point, where it seemed to work more reliably.

The problems regarding Outlook should have been reintroduced. I will have a look, if I can find another way around it.

**Comment by joten** [comment]
I tested it today and in the current development version it seems to be fixed.

**Comment by jfmcbrayer** [comment]
I have been using ff3e5ead3927993 for two days, and I agree that this appears to be fixed.
