### ISSUE TITLE
Cannot highlight focussed window

### ISSUE THREAD

**Issue by blokeley** [fuhsjr00/bug.n#217]
I need (want) the window with current focus to be obvious by having a coloured border like the top left window in the image below:

![Highlighted window](https://i.stack.imgur.com/qDdpG.png)

I have tried the following customisations in my Config.ini but they seem to have no effect. I'm guessing that colours are specified in hex RGB so 0000ff should be blue.

```
; Customise theme
Config_showBorder=1
Config_borderWidth=3
Config_selBorderColor=0000ff
```

Please could you advise the correct config?

I tried asking a [question on superuser](https://superuser.com/questions/1448640/how-to-highlight-focussed-window-using-bug-n) but got no answers.

**Comment by ertwro** [comment]
Highlighting a Window is a property of Windows, at least in Windows 10. This is configured in the windows settings. Since Bug.n uses <kbd>Win</kbd><kbd>i</kbd> to obtain properties about windows, you can use <kbd>Win</kbd><kbd>r</kbd> or `run` and introduce `ms-settings:colors` to access the `Settings>Personalization>Colors` menu. Once there pick a color and select `[-]Title bars and window borders`.

**Comment by blokeley** [comment]
Thanks for the help.  I set the theme to the standard "WIndows 10" one, but dark, turned on the "Title bars and window borders" and set to Blue (which it was already), and set the BorderWidth to -750 but it made no difference...

![image](https://user-images.githubusercontent.com/959543/59548267-c3fa0000-8f44-11e9-9987-38a521d8d4a1.png)

In the image above, it is almost impossible to tell which window is focussed.  It's the top right!

Strangely, the PowerPoint window has massive padding so maybe it has taken on the -750 twirp border?

Any ideas how to get a border?

**Comment by blokeley** [comment]
It seems that control over border width using `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics\BorderWidth` has been disabled in Windows 10.  I even tried turning on High Contrast themes but the border was even smaller!  I doubt that bug.n can do anything about this.

**Comment by ertwro** [comment]
@blokeley BorderWidth is not universally disabled but is unreliable as I said, since it's configuration and maybe version dependent (in both my machines v20H1 b18917 and v1903 b18362 works). In order for window borders to be differentiated, you need active and inactive properties. In your registry, you can edit these values if personalization didn't work for you.
```
# Registry Editor path (Copy & paste it in the Registry address bar)
HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM
# Modify the AccentColor
# Add the DWORD (32 bit value) - AccentColorInactive
# The value is a hexadecimal number
```
Naturally, this is all Windows 10 configuration dependent and not related to bug.n
![image](https://user-images.githubusercontent.com/29201466/59554075-bf910f80-8f63-11e9-8ae7-82f39eb4c662.png)

**Comment by blokeley** [comment]
@ertwro thanks for the very helpful tips. I tried the registry changes but no joy :(

**Comment by isc30** [comment]
same here, what a pity
