### ISSUE TITLE
Bug.n freeze when debugging a .net window application in VS2012

### ISSUE THREAD

**Issue by franckspike** [fuhsjr00/bug.n#30]
This is probably due to bug.n trying to communicate with the window while it cannot respond since it is under debugging

**Comment by joten** [comment]
This is difficult for me to reproduce, since I do not use Visual Studio 2012, nor do  I have some .NET-application or do any debugging.

Can you do some more testing? You may add the following line to your Config.ini: `Config_rule=.*;.*;Window_isElevated;0;0;0;1;1;0;` replacing the first two fields with the specific class or title of the window in question.

_bug.n_ can detect hung windows; but obviously there is another problem.

**Comment by franckspike** [comment]
I'll look for a way to detect when an application is under debugging and paused then I'll try just ignoring that window (or maybe temporarily doing as if elevated)

**Comment by joten** [comment]
Although I am a little late. -- Any news on this one?

**Comment by joten** [comment]
Not using Visual Studio 2012 and debugging .NET-applications, I cannot reproduce the problem.

**Comment by mattlyons0** [comment]
I can reproduce this with Visual Studio 2013 and can confirm the config rule solves the problem.

**Comment by kalj** [comment]
I see this when debugging C++ applications using Visual Studio 2015 too. I just started using bug.n today, and would be happy to understand what goes wrong here. Should I add a rule for the program I'm debugging in general (which is paused at breakpoints), or one which only 'hits' when it is paused? How can the latter be done?

**Comment by joten** [comment]
SInce I can not reproduce the issue, I am a bit lost here. @mattlyons0 suggested the rule `Config_rule=.*;.*;Window_isElevated;0;0;0;1;1;0;` with adjusted class and title regex (first two fields) solved the problem; it should be the class and title of the debugger window, I think.
