### ISSUE TITLE
Debugging help for rules?

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#42]
I noticed the nice addition to `#i` of the rule representing the current window state.

Is it possible to add ''which'' actual rule was used for this windows? (e.g., "configured by rule 2")

My problem is that I have a rule that doesn't seem to work:
`Config_rule=#32770;.*TortoiseSVN;;1;0;0;1;1;0;`
It should override rule 3 to let TortoiseSvn windows be managed and floating. It seems well-formed, matching `#i` info, but the windows still comes unmanaged. I even tried to make it rule 18 in `Config.ahk`, with no success. It worked well in 8.3.1.

I don't know what tools are available to confirm this kind of problems.

**Comment by louy2** [comment]
My TortoiseSVN windows does not have `TortoiseSVN` in their titles at all. Maybe you can try removing it: `Config_rule=#32770;.*;;1;0;0;1;1;0;`

**Comment by Chadehoc** [comment]
> My TortoiseSVN windows do not have `TortoiseSVN` in their titles at all.

Mine have... but you got it right: they first do not have it, for a very short time, then they change their title! Maybe tiling was done later in 8.3.1 (using the final title), or maybe I updated TortoiseSvn since I switched to using `master`. Thanks for pointing this.

Anyway, I keep the suggestion to add to the `#i` info which rules was triggered.

**Comment by joten** [comment]
The last matching rule is currently not tracked. The rule in the window-information-dialog is composed of the information, which is available within bug.n about the current state of the window.

Since you need some debugging information, I added the necessary information to `Debug_logMessage("DEBUG[1] Manager_applyRules: class: " wndClass ", title: " wndTitle ", wndId: " wndId ", rule #: " i, 1)`.

You may use `#^+d::Debug_setLogLevel(0, +1)` to increase the debugging level, open the window in question and than decrease the debugging level back to 0 with `#^d::Debug_setLogLevel(0, -1)`, if you do not want to spam the log (by default `C:\Users\<username>\AppData\Roaming\bug.n\log.txt`).

**Comment by Chadehoc** [comment]
> Since you need some debugging information, I added the necessary information

Thanks! It is exactly what I needed: in the log can see that the tile used at trigger time was not the one that finally appears. So it would have debugged my case.
