### ISSUE TITLE
Default_configuration.md has mistake

### ISSUE THREAD

**Issue by 010penetrator** [fuhsjr00/bug.n#46]
`Config_rule_#1=.*;.*;;1;0;0;0;0;0;`
> By default all windows are managed, not allocated on a specific monitor or
view, not floating (i. e. tiled), the window title bar is not visible, the
title is not hidden on the bug.n status bar and no window action is taken, when
the window first is created.

The parameter responsible for window title bar is actually next-to-last.

**Comment by joten** [comment]
Not as far as I know ;-)

bug.n/doc/Configuring_rules.md says
```
<is floating>;
<is decorated>;
<hide title>;
<action on a single window>
```
and  bug.n/src/Manager.ahk says in `Manager_applyRules`
```
isFloating  := rule7
isDecorated := rule8
hideTitle   := rule9
action      := rule10
```

"window title bar" means decoration, which is last but two.

From bug.n/doc/Configuring_rules.md:
> "Is the window decorated (0 = no, 1 = yes)? If not, the window title bar is removed."

The window's title, i. e. the text, is what is hidden from the bug.n status bar by setting the parameter next to last.

Or did I misunderstand the issue?

**Comment by 010penetrator** [comment]
Hi!
You get it right, but it is not working. Looks like hideTitle and isDecorated are twisted.
![proof](https://cloud.githubusercontent.com/assets/11810102/8856552/2c22d388-3174-11e5-8f14-9853f17e7261.png)

**Comment by joten** [comment]
> Looks like hideTitle and isDecorated are twisted.
Not twisted at least, since the title is not hidden on the bug.n status
bar as it should be by rule #1.

But you are right, for the shown window the default rule is not
working. The window title suggests, that Notepad++ is run as
administrator; if so, are you running bug.n as administrator as well?
If not, the problem will be, that programs run as administrator are not
handled by bug.n at all. Please see the following for more information:
https://github.com/fuhsjr00/bug.n/blob/master/doc/Installing_and_running.md#microsoft-windows-user-access-control

If the presiding assumptions are all wrong, do you have changed any
default reules or added new ones, or are you using vanilla bug.n?

**Comment by 010penetrator** [comment]
I have updated with July 16 bug.n-master.zip and checked again.
Second digit from right is responsible for the window title bar, while it is supposed to affect status bar.
Third digit from right makes no effect. 
There is only one user and UAC is off on that PC, so everything is run by administrator.

**Comment by joten** [comment]
I have to admit, I still quite don't understand. -- Therefor I did some elaborate testing... It all works as expected, except that the window information is getting the wrong result for "hide title". -- I will fix that, of course.

The second digit from right is supposed to affect the window title bar. The third digit from right affects the tiling of the window, i. e. makes it floating. The last semicolon separates the last parameter, which is "action" (e. g. maximize), although most times it is left blank.

![bug n_11](https://cloud.githubusercontent.com/assets/6839361/11820982/8dc1bc52-a367-11e5-8183-d12039802b91.png)
![bug n_21](https://cloud.githubusercontent.com/assets/6839361/11820985/9282df82-a367-11e5-918c-6d065411e717.png)

![bug n_10](https://cloud.githubusercontent.com/assets/6839361/11820979/8abd165a-a367-11e5-9663-d2cecfde3811.png)
![bug n_20](https://cloud.githubusercontent.com/assets/6839361/11820984/901d667c-a367-11e5-8de9-e4040cccfc5a.png)
![bug n_30](https://cloud.githubusercontent.com/assets/6839361/11820987/940c5cd4-a367-11e5-9fee-170353feae2e.png)
![bug n_40](https://cloud.githubusercontent.com/assets/6839361/11820988/959d8564-a367-11e5-986c-629b832940e8.png)

Please regard, that the screenshots with a "Window Information" pop-up in focus don't show a title in the status bar, because titles from pop-up windows are hidden; it has nothing to do with the notepad window.

From your screenshot I take it that your default rule is `Config_rule_#1=.*;.*;;1;0;0;0;1;0;`, which indeed matches the window shown; i. e. it is decorated (has a title bar) and the title is not hidden from the status bar.

**Comment by 010penetrator** [comment]
My OS installation and theming was identical on both computers I tried the
thing. That may have been the source of the problem... I am not using
Windows by now.
Thanks for your time!
4 янв. 2016 г. 23:14 пользователь "joten" <notifications@github.com>
написал:
