### ISSUE TITLE
Default shortcuts incompatible with Model M keyboard

### ISSUE THREAD

**Issue by Reyncor** [fuhsjr00/bug.n#53]
A more mouse friendly interface or non Super key dependent hotkeys would be nice.

Another issue is that Config.ini is created with a Super key shortcut, which makes it increasingly difficult to change that.

**Comment by joten** [comment]
Hm, I do understand the difficulties -- though not from experience.

> A more mouse friendly interface

I don't think so. bug.n arose from the urge to manage windows by keyboard. Although code has been added with commit c12a2660447b44d1de55c57d22f12179aa0f3e2a, which allows some kind of a remote control from an external script, as suggested by franckspike with issue #20.

Regarding the issue of creating a `Config.ini`, you may use [this Config_template.ini](https://github.com/joten/bug.n.config/blob/master/Config_template.ini). -- I hope it is accurate. You may also run bug.n as an AutoHotkey script and directly edit `Config.ahk` preventing the use of a `Config.ini`.

The usage of the Super key in the default configuration is due to the general avoidance of conflicts with application specific hotkeys. 

If you like, you may create a `Config.ini`to your liking, which than can be integrated in the documentation like the (deprecated) one in Xmonad-style in [bug.n/doc/User-hotkeys.md](https://github.com/fuhsjr00/bug.n/blob/master/doc/User-hotkeys.md).

**Comment by joten** [comment]
Although not in the easiest way, the issue should be solved.
