### ISSUE TITLE
Compatible keymap for non-QWERTY keyboard layouts

### ISSUE THREAD

**Issue by palra** [fuhsjr00/bug.n#55]
I have an AZERTY keyboard, and the `#<n>` key binding does not work as the number keys above the letter section are not assigned to the same characters. `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9` and `0` triggers respectively `&`, `é`, `"`, `'`, `(`, `-`, `è`, `_`, `ç` and `à` in such a layout.

For the moment, I modified my `Config.ini` in order to make view/tags key bindings work, but it would be great if bug.n automatically detects the current keyboard layout and loads the correct key bindings.

(I don't have access to my modified `Config.ini` while writing this, but I will add it toworrow)

Maybe linked with #53

**Comment by joten** [comment]
> Maybe linked with #53

Yes. The problem is, that the current default hotkeys are the ones with the fewest conflicts (the Super key and the common keys between the QWERTZ and QWERTY keyboard layout). It would be possible to determine the current keyboard layout, I think, but it would mean to selectively overwrite the default hotkeys, which can already be done in a more general way by setting them in `Config.ini`.

Therefor, if you like, you may create a `Config.ini`, which works best for you, and which than can be integrated in [bug.n/doc/User-hotkeys.md](https://github.com/fuhsjr00/bug.n/blob/master/doc/User-hotkeys.md). Perhaps we will create a user directory, in which all user-`Config.ini`-files are saved to allow a more convenient access to different configurations.

**Comment by taohansen** [comment]
I think this still isn't solved. I use Programmer's Dvorak on a Kinesis. On Linux, applications transparently handle whatever crazy layout you can think of. I don't mind using your default shortcuts. I just fail to see why my keystrokes aren't interpreted as they're typed.

**Comment by 3dc1d3** [comment]
I'm using Portable Keyboard Layout, which uses AHK under the hood, and I have the same issue: bug.n ignores the remapping of the layout, treating keys as per qwerty.

I assumed they'd play nice since both rely on AHK.
