### ISSUE TITLE
chrome generate a blank window when loading a page

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#79]
When I open a new page or refresh an old one, once it cann't be loaded immediately, chrome will generate a new blank window and the previous one will lost its maximum state.
The new window has no title and can not be seen(sometimes a piece of white with 'is loading' text is there), but can be captured by win+i, below is the result. For the class is just the same as chrome, i don't know how to manage or escape it.

>ID: 0xc13ec
class:	Chrome_WidgetWin_1
title:	
process:	chrome.exe [8140]
style:	0x96000000
metrics:	x: 247, y: 870, width: 448, height: 64
tags:	2

>Config_rule=Chrome_WidgetWin_1;;;1;1;2;0;0;0;`

**Comment by joten** [comment]
There has been an issue just like that a long while ago, it was fixed, but later the code was removed again, because it seemed to be not needed anymore. I found it version 8.3.0 -- at least.
```
WinGet, wndProcessName, ProcessName, ahk_id %wndId%
  If (wndProcessName = "chrome.exe") 
  {
    WinGet, wndControlList, ControlList, ahk_id %wndId%
    StringSplit, c, wndControlList, `n
    If (c0 <= 1)
      isManaged := False
  }
```
I will have to see, what I can make about the code.

**Comment by qijianjun** [comment]
@joten Chrome:48.0.2564.116m; bug.n:0.90

There is some other info:
When the page loaded done, the window is no longer fill in the screen, I have to use win+right to maximize it again.

**Comment by janus0** [comment]
I've had this issue as well, particularly when the drop down box pops up on chrome saying "extension installed"

**Comment by joten** [comment]
Do you mean version 9.0.0-beta.1 or the current development version? In the latter I found `;; @TODO [v9] Config_rule_#13 := "Chrome_WidgetWin_1;.*;0x80000000;0;0;0;1;1;0;"  -- else pop-up windows are treated as new main windows, since #12 overrides #2`.

Nevertheless I reverted the current development version to the commit right after the release of version 9.0.0-beta.1. Please ensure that you have `Config_rule_#13  := "Chrome_WidgetWin_1;.*;Window_isPopup;0;0;0;1;1;0;"` in your `Config.ahk` and test it with this version.

If the issue remains, I will reimplement the code above in a separate function and make it available via `Config.ini`.

**Comment by qijianjun** [comment]
I find the problem.
I added one line in config.ini, it overwrites the default config for chrome:
>;Config_rule=Chrome_WidgetWin_1;.*;;1;0;2;0;0;0;maximize

I remove it and all is ok.

9.0.0.-beta.1 and the current development version on wiki index page both perform well with the corrected config.ini.
